"""GENERATED by scripts/workbench/schemas.mjs from packages/domain/3d-core/types.ts; edit the types, then run it.

The keywords of each 3D element as a TypedDict (``extrude(**props)`` takes ``ExtrudeProps``), and the definitions their
values are made of (camelCase keys, as stored). The reader checks the same fields against ``SCHEMA`` (threed_schema.py)
and refuses a wrong one with the sentence an op panel shows."""
from typing import Any, Dict, List, Tuple, Union

try:
    from typing import Literal, TypedDict
except ImportError:  # pragma: no cover
    from typing_extensions import Literal, TypedDict  # type: ignore

__AxisRef1Required = TypedDict("__AxisRef1Required", {"type": Literal["datumAxis"], "axis": Literal["X", "Y", "Z"]})
__AxisRef1Optional = TypedDict("__AxisRef1Optional", {}, total=False)
class _AxisRef1(__AxisRef1Required, __AxisRef1Optional):
    pass

__AxisRef2Required = TypedDict("__AxisRef2Required", {"type": Literal["sketchLine"], "sketch": str, "segment": str})
__AxisRef2Optional = TypedDict("__AxisRef2Optional", {}, total=False)
class _AxisRef2(__AxisRef2Required, __AxisRef2Optional):
    pass

__AxisRef3Required = TypedDict("__AxisRef3Required", {"type": Literal["edge"], "ref": 'TopoRef'})
__AxisRef3Optional = TypedDict("__AxisRef3Optional", {}, total=False)
class _AxisRef3(__AxisRef3Required, __AxisRef3Optional):
    pass

__AxisRef4Required = TypedDict("__AxisRef4Required", {"type": Literal["points"], "a": 'Vec3', "b": 'Vec3'})
__AxisRef4Optional = TypedDict("__AxisRef4Optional", {}, total=False)
class _AxisRef4(__AxisRef4Required, __AxisRef4Optional):
    pass

_BoxFeatureRequired = TypedDict("_BoxFeatureRequired", {"type": Literal["box"], "center": 'Vec3', "size": 'Vec3', "operation": 'BooleanMode', "id": str, "name": str})
_BoxFeatureOptional = TypedDict("_BoxFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class BoxFeature(_BoxFeatureRequired, _BoxFeatureOptional):
    pass

_ChamferFeatureRequired = TypedDict("_ChamferFeatureRequired", {"type": Literal["chamfer"], "edges": List['TopoRef'], "distance": float, "id": str, "name": str})
_ChamferFeatureOptional = TypedDict("_ChamferFeatureOptional", {"distance2": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ChamferFeature(_ChamferFeatureRequired, _ChamferFeatureOptional):
    pass

#: What a chart's map does to lengths, without the samples. The domain's honest self-description.
_ChartDistortionSummaryRequired = TypedDict("_ChartDistortionSummaryRequired", {"chart": str, "scaleMin": float, "scaleMax": float, "areaScaleMin": float, "areaScaleMax": float, "maxDilatation": float, "isometric": bool, "tolerance": float})
_ChartDistortionSummaryOptional = TypedDict("_ChartDistortionSummaryOptional", {}, total=False)
class ChartDistortionSummary(_ChartDistortionSummaryRequired, _ChartDistortionSummaryOptional):
    pass

#: WHICH EDGE of a chart — an isoparametric curve, named the way a b-rep names one.
_ChartEdgeRequired = TypedDict("_ChartEdgeRequired", {"param": Literal["u", "v"], "at": float, "from": float, "to": float})
_ChartEdgeOptional = TypedDict("_ChartEdgeOptional", {}, total=False)
class ChartEdge(_ChartEdgeRequired, _ChartEdgeOptional):
    pass

#: A rigid placement of a chart's local frame in the flat domain. Rotation + translation only.
_ChartPlacementRequired = TypedDict("_ChartPlacementRequired", {"origin": 'Vec2', "angle": float})
_ChartPlacementOptional = TypedDict("_ChartPlacementOptional", {"mirror": bool}, total=False)
class ChartPlacement(_ChartPlacementRequired, _ChartPlacementOptional):
    pass

_CircularPatternFeatureRequired = TypedDict("_CircularPatternFeatureRequired", {"type": Literal["circularPattern"], "seedFeature": str, "axis": 'AxisRef', "count": int, "id": str, "name": str})
_CircularPatternFeatureOptional = TypedDict("_CircularPatternFeatureOptional", {"angle": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CircularPatternFeature(_CircularPatternFeatureRequired, _CircularPatternFeatureOptional):
    pass

#: A PART AUTHORED AS CODE (docs/wave-h.md §3): a `.ts` / `.tsx` / `.js` / `.jsx` / `.py` file, beside the document, that declares features with the CommandAGI SDK (or JSCAD, replicad or CadQuery through its importers). Opening the part runs the file in the sandbox with `inputs` and puts what it declares in this feature's place: the file's result takes this feature's id, so a feature that `consumes` it follows the code part. It is the one feature of its file that is saved.
_CodeFeatureRequired = TypedDict("_CodeFeatureRequired", {"type": Literal["code"], "source": str, "id": str, "name": str})
_CodeFeatureOptional = TypedDict("_CodeFeatureOptional", {"inputs": Dict[str, Any], "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CodeFeature(_CodeFeatureRequired, _CodeFeatureOptional):
    pass

_CoilFeatureRequired = TypedDict("_CoilFeatureRequired", {"type": Literal["coil"], "profile": 'ProfileRef', "axis": 'AxisRef', "pitch": float, "turns": float, "operation": 'BooleanMode', "id": str, "name": str})
_CoilFeatureOptional = TypedDict("_CoilFeatureOptional", {"rightHanded": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CoilFeature(_CoilFeatureRequired, _CoilFeatureOptional):
    pass

_CombineFeatureRequired = TypedDict("_CombineFeatureRequired", {"type": Literal["combine"], "operation": Literal["intersect", "union", "subtract"], "id": str, "name": str})
_CombineFeatureOptional = TypedDict("_CombineFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CombineFeature(_CombineFeatureRequired, _CombineFeatureOptional):
    pass

#: A placed component's footprint — the pads it contributes, and the planes they land on.
_ComponentFootprintRequired = TypedDict("_ComponentFootprintRequired", {"pads": List['FootprintPad'], "layers": List['CopperLayerRef']})
_ComponentFootprintOptional = TypedDict("_ComponentFootprintOptional", {"libId": str, "part": str}, total=False)
class ComponentFootprint(_ComponentFootprintRequired, _ComponentFootprintOptional):
    pass

#: THE ELECTRICAL HALF OF A CONDUCTOR, declared on an ORDINARY 3D body.
_ConductorElectricalRequired = TypedDict("_ConductorElectricalRequired", {"conductivitySPerM": float, "finishedThicknessMm": float, "dielectricEpsR": float})
_ConductorElectricalOptional = TypedDict("_ConductorElectricalOptional", {}, total=False)
class ConductorElectrical(_ConductorElectricalRequired, _ConductorElectricalOptional):
    pass

#: THE 0D RUNG, as a reference: an ORDERED run of points inside one sketch.
_ConductorPathRefRequired = TypedDict("_ConductorPathRefRequired", {"sketch": str, "points": List[str]})
_ConductorPathRefOptional = TypedDict("_ConductorPathRefOptional", {"breakAfter": List[str]}, total=False)
class ConductorPathRef(_ConductorPathRefRequired, _ConductorPathRefOptional):
    pass

_ConeFeatureRequired = TypedDict("_ConeFeatureRequired", {"type": Literal["cone"], "center": 'Vec3', "axis": 'Vec3', "radius1": float, "radius2": float, "height": float, "operation": 'BooleanMode', "id": str, "name": str})
_ConeFeatureOptional = TypedDict("_ConeFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ConeFeature(_ConeFeatureRequired, _ConeFeatureOptional):
    pass

#: A cone: `S(u,v) = origin + (R + v·sinα)(cos u·x + sin u·y) + v·cosα·axis`, `α` the half-angle. `R` is the radius at `v = 0`. A constant-radius bevel between two planar faces is a portion of exactly this or of a cylinder, which is why the motivating MID case is the EXACT one.
_ConicalSurfaceRequired = TypedDict("_ConicalSurfaceRequired", {"kind": Literal["cone"], "radius": float, "halfAngle": float, "origin": 'Vec3', "xAxis": 'Vec3', "yAxis": 'Vec3', "axis": 'Vec3'})
_ConicalSurfaceOptional = TypedDict("_ConicalSurfaceOptional", {}, total=False)
class ConicalSurface(_ConicalSurfaceRequired, _ConicalSurfaceOptional):
    pass

#: WHICH COPPER LAYER a conductor lives on — its name and the datum plane it is drawn in.
_CopperLayerRefRequired = TypedDict("_CopperLayerRefRequired", {"name": str})
_CopperLayerRefOptional = TypedDict("_CopperLayerRefOptional", {"plane": str}, total=False)
class CopperLayerRef(_CopperLayerRefRequired, _CopperLayerRefOptional):
    pass

#: A COPPER POUR — A REGION SWEPT ON A PLANE, and the second special case that disappears.
_CopperPourFeatureRequired = TypedDict("_CopperPourFeatureRequired", {"type": Literal["copperPour"], "path": 'ConductorPathRef', "layer": 'CopperLayerRef', "rule": 'RoutingRule', "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str, "name": str})
_CopperPourFeatureOptional = TypedDict("_CopperPourFeatureOptional", {"bias": 'RouteBias', "material": 'MaterialDef', "bindings": List['TerminalBinding'], "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CopperPourFeature(_CopperPourFeatureRequired, _CopperPourFeatureOptional):
    pass

_CopyBodyFeatureRequired = TypedDict("_CopyBodyFeatureRequired", {"type": Literal["copyBody"], "bodyId": str, "id": str, "name": str})
_CopyBodyFeatureOptional = TypedDict("_CopyBodyFeatureOptional", {"translate": 'Vec3', "rotateAxis": 'AxisRef', "rotateAngle": float, "count": int, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CopyBodyFeature(_CopyBodyFeatureRequired, _CopyBodyFeatureOptional):
    pass

_CylinderFeatureRequired = TypedDict("_CylinderFeatureRequired", {"type": Literal["cylinder"], "center": 'Vec3', "axis": 'Vec3', "radius": float, "height": float, "operation": 'BooleanMode', "id": str, "name": str})
_CylinderFeatureOptional = TypedDict("_CylinderFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class CylinderFeature(_CylinderFeatureRequired, _CylinderFeatureOptional):
    pass

#: A cylinder: `S(u,v) = origin + R(cos u·x + sin u·y) + v·axis`. `u` is an ANGLE, `v` a length — OCC's own convention, and the reason "we already have uv, sketch in it" measures wrong: a step in `u` is `R` millimetres, not one.
_CylindricalSurfaceRequired = TypedDict("_CylindricalSurfaceRequired", {"kind": Literal["cylinder"], "radius": float, "origin": 'Vec3', "xAxis": 'Vec3', "yAxis": 'Vec3', "axis": 'Vec3'})
_CylindricalSurfaceOptional = TypedDict("_CylindricalSurfaceOptional", {}, total=False)
class CylindricalSurface(_CylindricalSurfaceRequired, _CylindricalSurfaceOptional):
    pass

_DatumPlaneFeatureRequired = TypedDict("_DatumPlaneFeatureRequired", {"type": Literal["datumPlane"], "base": str, "offset": float, "id": str, "name": str})
_DatumPlaneFeatureOptional = TypedDict("_DatumPlaneFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class DatumPlaneFeature(_DatumPlaneFeatureRequired, _DatumPlaneFeatureOptional):
    pass

_DeleteFaceFeatureRequired = TypedDict("_DeleteFaceFeatureRequired", {"type": Literal["deleteFace"], "faces": List['TopoRef'], "id": str, "name": str})
_DeleteFaceFeatureOptional = TypedDict("_DeleteFaceFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class DeleteFaceFeature(_DeleteFaceFeatureRequired, _DeleteFaceFeatureOptional):
    pass

#: How far a patch is from flattenable, and by how much.
_DevelopabilityVerdictRequired = TypedDict("_DevelopabilityVerdictRequired", {"developable": bool, "totalAbsoluteCurvature": float, "tolerance": float, "maxAbsCurvature": float, "area": float})
_DevelopabilityVerdictOptional = TypedDict("_DevelopabilityVerdictOptional", {"because": str}, total=False)
class DevelopabilityVerdict(_DevelopabilityVerdictRequired, _DevelopabilityVerdictOptional):
    pass

_DomeFeatureRequired = TypedDict("_DomeFeatureRequired", {"type": Literal["dome"], "face": 'TopoRef', "height": float, "id": str, "name": str})
_DomeFeatureOptional = TypedDict("_DomeFeatureOptional", {"rings": int, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class DomeFeature(_DomeFeatureRequired, _DomeFeatureOptional):
    pass

_DraftFeatureRequired = TypedDict("_DraftFeatureRequired", {"type": Literal["draft"], "faces": List['TopoRef'], "angle": float, "pullDirection": 'Vec3', "id": str, "name": str})
_DraftFeatureOptional = TypedDict("_DraftFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class DraftFeature(_DraftFeatureRequired, _DraftFeatureOptional):
    pass

#: A LINKED (not embedded) part reference. Unlike ImportFeature — which copies the foreign STEP/IGES bytes into the document — an `ExternalPartRef` only records *where* to find another Drive file (by id or name) and reloads it on open. This keeps a part reusable across assemblies and lets a part edit propagate to every place it's used. The reference system (`cad/references.ts`) turns these into `FileRef`s (`role:"part"`); the editor resolves + meshes them. Foreign solids carry an `importer` ("step"/"iges") so the resolver knows to run the import path rather than run a `.3d.tsx`.
_ExternalPartRefRequired = TypedDict("_ExternalPartRefRequired", {"type": Literal["externalPart"], "placement": 'Placement', "operation": 'BooleanMode', "id": str, "name": str})
_ExternalPartRefOptional = TypedDict("_ExternalPartRefOptional", {"fileId": str, "path": str, "fileName": str, "importer": Literal["step", "iges", "3d", "wrl", "glb", "gltf", "obj", "stl", "ply", "3mf", "fbx", "dae", "usd", "kicad_pcb", "pcb.tsx"], "unitScaleMm": float, "component": str, "localPlacement": 'Placement', "footprint": 'ComponentFootprint', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ExternalPartRef(_ExternalPartRefRequired, _ExternalPartRefOptional):
    pass

_ExtrudeFeatureRequired = TypedDict("_ExtrudeFeatureRequired", {"type": Literal["extrude"], "profile": 'ProfileRef', "distance": float, "operation": 'BooleanMode', "id": str, "name": str})
_ExtrudeFeatureOptional = TypedDict("_ExtrudeFeatureOptional", {"symmetric": bool, "reverse": bool, "distance2": float, "draftAngle": float, "through": bool, "upToFace": 'TopoRef', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ExtrudeFeature(_ExtrudeFeatureRequired, _ExtrudeFeatureOptional):
    pass

_FilletFeatureRequired = TypedDict("_FilletFeatureRequired", {"type": Literal["fillet"], "edges": List['TopoRef'], "radius": float, "id": str, "name": str})
_FilletFeatureOptional = TypedDict("_FilletFeatureOptional", {"radius2": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class FilletFeature(_FilletFeatureRequired, _FilletFeatureOptional):
    pass

#: A FITTED flattening, stored as a tensor-product Bernstein map over the chart's own (u,v) rectangle.
_FittedChartMapRequired = TypedDict("_FittedChartMapRequired", {"kind": Literal["fitted"], "degreeU": float, "degreeV": float, "x": List[List[float]], "y": List[List[float]], "scaffold": float, "residual": float})
_FittedChartMapOptional = TypedDict("_FittedChartMapOptional", {}, total=False)
class FittedChartMap(_FittedChartMapRequired, _FittedChartMapOptional):
    pass

#: ONE PAD of a component's footprint, in the copper-layer plane's own (u,v) millimetres relative to the placement origin.
_FootprintPadRequired = TypedDict("_FootprintPadRequired", {"terminal": str, "layer": str, "at": Tuple[float, float]})
_FootprintPadOptional = TypedDict("_FootprintPadOptional", {"size": Tuple[float, float]}, total=False)
class FootprintPad(_FootprintPadRequired, _FootprintPadOptional):
    pass

_FullRoundFeatureRequired = TypedDict("_FullRoundFeatureRequired", {"type": Literal["fullRound"], "face": 'TopoRef', "id": str, "name": str})
_FullRoundFeatureOptional = TypedDict("_FullRoundFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class FullRoundFeature(_FullRoundFeatureRequired, _FullRoundFeatureOptional):
    pass

__GaussianSplatFeature5Required = TypedDict("__GaussianSplatFeature5Required", {})
__GaussianSplatFeature5Optional = TypedDict("__GaussianSplatFeature5Optional", {"format": str, "fileId": str, "fileName": str, "shDegree": float, "splatCount": float}, total=False)
class _GaussianSplatFeature5(__GaussianSplatFeature5Required, __GaussianSplatFeature5Optional):
    pass

#: A **3D Gaussian-Splat volume** — the headline volumetric primitive: a cloud of anisotropic translucent gaussians (position + per-axis scale + orientation + color/opacity), the representation of choice for photoreal capture (video/scan → navigable scene) and volumetric science visualization. Imported from a gaussian PLY (or `.splat`); the DC spherical-harmonic term is baked to an RGB color on import.
_GaussianSplatFeatureRequired = TypedDict("_GaussianSplatFeatureRequired", {"type": Literal["gaussianSplat"], "count": float, "positions": List[float], "scales": List[float], "rotations": List[float], "colors": List[float], "id": str, "name": str})
_GaussianSplatFeatureOptional = TypedDict("_GaussianSplatFeatureOptional", {"shDegree": Literal[0, 3, 1, 2], "sh": List[float], "source": '_GaussianSplatFeature5', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class GaussianSplatFeature(_GaussianSplatFeatureRequired, _GaussianSplatFeatureOptional):
    pass

__GenNodeRecord6Required = TypedDict("__GenNodeRecord6Required", {"locator": str})
__GenNodeRecord6Optional = TypedDict("__GenNodeRecord6Optional", {"digest": str}, total=False)
class _GenNodeRecord6(__GenNodeRecord6Required, __GenNodeRecord6Optional):
    pass

#: The record a node holds: the output's locator always, the provenance fields when the run returned them. A run that returned only a file still records where its bytes are, in the same slot.
_GenNodeRecordRequired = TypedDict("_GenNodeRecordRequired", {"output": '_GenNodeRecord6'})
_GenNodeRecordOptional = TypedDict("_GenNodeRecordOptional", {"operator": str, "implementation": str, "implementationVersion": str, "artifactDigest": str, "artifactImmutable": bool, "inputDigest": str, "paramsDigest": str, "producedAt": str}, total=False)
class GenNodeRecord(_GenNodeRecordRequired, _GenNodeRecordOptional):
    pass

#: A GENERATE feature — a creative generative model (`@commandagi/core` `GEN_MODELS`) as a re-runnable node in the feature graph. It projects into the op-graph dock as a `gen:<modelId>` GenNode (see ui/model/opgraph-projection): scalar inputs (prompt/enum/…) ride in `params`, wired image/mesh inputs in `refs` (inputKey → upstream featureId), and running it (the dock's async `runNode`) generates an asset that lands as a separate splat/mesh feature (`addSciFeature`) and bakes its `provenance` record here. The generate feature itself produces no geometry — it's the recipe; the landed feature is the result.
_GenerateFeatureRequired = TypedDict("_GenerateFeatureRequired", {"type": Literal["generate"], "modelId": str, "params": Dict[str, Any], "id": str, "name": str})
_GenerateFeatureOptional = TypedDict("_GenerateFeatureOptional", {"refs": Dict[str, str], "provenance": 'GenNodeRecord', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class GenerateFeature(_GenerateFeatureRequired, _GenerateFeatureOptional):
    pass

#: A VIA — sketch points into an op, exactly like a trace, and that sameness is the evidence the decomposition is a real structure rather than a convenient one.
_GenerateViaFeatureRequired = TypedDict("_GenerateViaFeatureRequired", {"type": Literal["generateVia"], "at": 'ConductorPathRef', "layers": List['CopperLayerRef'], "drillMm": float, "padDiameterMm": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str, "name": str})
_GenerateViaFeatureOptional = TypedDict("_GenerateViaFeatureOptional", {"material": 'MaterialDef', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class GenerateViaFeature(_GenerateViaFeatureRequired, _GenerateViaFeatureOptional):
    pass

__GraphFeature7Required = TypedDict("__GraphFeature7Required", {})
__GraphFeature7Optional = TypedDict("__GraphFeature7Optional", {"format": str, "fileId": str, "fileName": str, "title": str, "nodeCount": float, "edgeCount": float}, total=False)
class _GraphFeature7(__GraphFeature7Required, __GraphFeature7Optional):
    pass

#: A **graph / network** — nodes at 3D positions joined by edges. The substrate for a CONNECTOME (nodes = cells/neurons, edges = synapses/contacts): "a Drosophila brain with exact cell mappings", a C. elegans wiring diagram, a protein-interaction net, a pipe/circuit network. Kernel-free; rendered as node spheres + edge lines. Distinct from `skeleton` (a within-cell branching tree) — this is the between-cell wiring.
_GraphFeatureRequired = TypedDict("_GraphFeatureRequired", {"type": Literal["graph"], "nodePositions": List[float], "edges": List[float], "id": str, "name": str})
_GraphFeatureOptional = TypedDict("_GraphFeatureOptional", {"nodeSizes": List[float], "nodeColors": List[float], "nodeGroups": List[float], "edgeWeights": List[float], "directed": bool, "source": '_GraphFeature7', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class GraphFeature(_GraphFeatureRequired, _GraphFeatureOptional):
    pass

_HoleFeatureRequired = TypedDict("_HoleFeatureRequired", {"type": Literal["hole"], "face": 'TopoRef', "diameter": float, "depth": float, "style": 'HoleStyle', "id": str, "name": str})
_HoleFeatureOptional = TypedDict("_HoleFeatureOptional", {"through": bool, "headDiameter": float, "headDepth": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class HoleFeature(_HoleFeatureRequired, _HoleFeatureOptional):
    pass

_ImportFeatureRequired = TypedDict("_ImportFeatureRequired", {"type": Literal["import"], "format": Literal["step", "iges"], "data": str, "operation": 'BooleanMode', "id": str, "name": str})
_ImportFeatureOptional = TypedDict("_ImportFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ImportFeature(_ImportFeatureRequired, _ImportFeatureOptional):
    pass

_LinearPatternFeatureRequired = TypedDict("_LinearPatternFeatureRequired", {"type": Literal["linearPattern"], "seedFeature": str, "direction": 'Vec3', "spacing": float, "count": int, "id": str, "name": str})
_LinearPatternFeatureOptional = TypedDict("_LinearPatternFeatureOptional", {"direction2": 'Vec3', "spacing2": float, "count2": int, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class LinearPatternFeature(_LinearPatternFeatureRequired, _LinearPatternFeatureOptional):
    pass

_LoftFeatureRequired = TypedDict("_LoftFeatureRequired", {"type": Literal["loft"], "profiles": List['ProfileRef'], "operation": 'BooleanMode', "id": str, "name": str})
_LoftFeatureOptional = TypedDict("_LoftFeatureOptional", {"ruled": bool, "closed": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class LoftFeature(_LoftFeatureRequired, _LoftFeatureOptional):
    pass

#: A REAL human body: MakeHuman's hm08 basemesh morphed by its macro targets.
_MakeHumanFeatureRequired = TypedDict("_MakeHumanFeatureRequired", {"type": Literal["makeHuman"], "id": str, "name": str, "gender": float, "age": float, "muscle": float, "weight": float, "height": float, "proportions": float, "cupsize": float, "firmness": float, "african": float, "asian": float, "caucasian": float})
_MakeHumanFeatureOptional = TypedDict("_MakeHumanFeatureOptional", {"subdivision": int, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class MakeHumanFeature(_MakeHumanFeatureRequired, _MakeHumanFeatureOptional):
    pass

_MaterialDefRequired = TypedDict("_MaterialDefRequired", {"preset": 'MaterialPreset', "color": str, "metalness": float, "roughness": float, "envIntensity": float})
_MaterialDefOptional = TypedDict("_MaterialDefOptional", {"opacity": float}, total=False)
class MaterialDef(_MaterialDefRequired, _MaterialDefOptional):
    pass

__MeshBodyFeature8Required = TypedDict("__MeshBodyFeature8Required", {})
__MeshBodyFeature8Optional = TypedDict("__MeshBodyFeature8Optional", {"prompt": str, "expert": str, "generationId": str, "fileId": str, "fileName": str}, total=False)
class _MeshBodyFeature8(__MeshBodyFeature8Required, __MeshBodyFeature8Optional):
    pass

_MeshBodyFeatureRequired = TypedDict("_MeshBodyFeatureRequired", {"type": Literal["meshBody"], "positions": List[float], "indices": List[float], "id": str, "name": str})
_MeshBodyFeatureOptional = TypedDict("_MeshBodyFeatureOptional", {"polygons": List[List[float]], "normals": List[float], "uv": List[float], "sourceUv": List[float], "sourceMaterials": List['SourceMaterial'], "materialGroups": List['SourceMaterialGroup'], "source": '_MeshBodyFeature8', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class MeshBodyFeature(_MeshBodyFeatureRequired, _MeshBodyFeatureOptional):
    pass

#: One editable operation over another mesh-producing source node. References are graph edges.
_MeshModifierFeatureRequired = TypedDict("_MeshModifierFeatureRequired", {"type": Literal["meshModifier"], "input": str, "modifier": 'MeshModifierSpec', "id": str, "name": str})
_MeshModifierFeatureOptional = TypedDict("_MeshModifierFeatureOptional", {"target": str, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class MeshModifierFeature(_MeshModifierFeatureRequired, _MeshModifierFeatureOptional):
    pass

__MeshModifierSpec9Required = TypedDict("__MeshModifierSpec9Required", {"kind": Literal["displace"], "distance": float})
__MeshModifierSpec9Optional = TypedDict("__MeshModifierSpec9Optional", {"normalWeighting": Literal["angle", "area"]}, total=False)
class _MeshModifierSpec9(__MeshModifierSpec9Required, __MeshModifierSpec9Optional):
    pass

__MeshModifierSpec10Required = TypedDict("__MeshModifierSpec10Required", {"kind": Literal["smooth"], "iterations": float, "factor": float})
__MeshModifierSpec10Optional = TypedDict("__MeshModifierSpec10Optional", {"preserveBoundary": bool}, total=False)
class _MeshModifierSpec10(__MeshModifierSpec10Required, __MeshModifierSpec10Optional):
    pass

__MeshModifierSpec11Required = TypedDict("__MeshModifierSpec11Required", {"kind": Literal["subdivide"], "levels": float})
__MeshModifierSpec11Optional = TypedDict("__MeshModifierSpec11Optional", {"limitSurface": bool}, total=False)
class _MeshModifierSpec11(__MeshModifierSpec11Required, __MeshModifierSpec11Optional):
    pass

__MeshModifierSpec12Required = TypedDict("__MeshModifierSpec12Required", {"kind": Literal["solidify"], "thickness": float})
__MeshModifierSpec12Optional = TypedDict("__MeshModifierSpec12Optional", {"normalWeighting": Literal["angle", "area"]}, total=False)
class _MeshModifierSpec12(__MeshModifierSpec12Required, __MeshModifierSpec12Optional):
    pass

__MeshModifierSpec13Required = TypedDict("__MeshModifierSpec13Required", {"kind": Literal["shrinkwrap"], "offset": float})
__MeshModifierSpec13Optional = TypedDict("__MeshModifierSpec13Optional", {}, total=False)
class _MeshModifierSpec13(__MeshModifierSpec13Required, __MeshModifierSpec13Optional):
    pass

_MirrorFeatureRequired = TypedDict("_MirrorFeatureRequired", {"type": Literal["mirror"], "plane": 'PlaneRef', "id": str, "name": str})
_MirrorFeatureOptional = TypedDict("_MirrorFeatureOptional", {"seedFeature": str, "keepOriginal": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class MirrorFeature(_MirrorFeatureRequired, _MirrorFeatureOptional):
    pass

__MoleculeFeature14Required = TypedDict("__MoleculeFeature14Required", {})
__MoleculeFeature14Optional = TypedDict("__MoleculeFeature14Optional", {"format": str, "fileId": str, "fileName": str, "title": str, "atomCount": float}, total=False)
class _MoleculeFeature14(__MoleculeFeature14Required, __MoleculeFeature14Optional):
    pass

#: A **molecular structure** — atoms + bonds (+ optional periodic cell), the substrate for real molecular maps of cells, protein/DNA assemblies, and atomically-precise nano-engineering. Imported from the chemistry/crystallography format zoo (PDB, mmCIF, SDF/MOL, MOL2, XYZ, CIF). Kernel-free; rendered ball-and-stick / space-filling. Positions are in ÅNGSTRÖM (rendered scaled) — molecules live at a different scale than mm 3D, so the viewport scales atoms into view; we keep the true Å coordinates.
_MoleculeFeatureRequired = TypedDict("_MoleculeFeatureRequired", {"type": Literal["molecule"], "positions": List[float], "elements": List[float], "bonds": List[float], "id": str, "name": str})
_MoleculeFeatureOptional = TypedDict("_MoleculeFeatureOptional", {"bondOrders": List[float], "chains": List[float], "cell": Tuple[float, float, float, float, float, float], "representation": 'MoleculeRepresentation', "source": '_MoleculeFeature14', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class MoleculeFeature(_MoleculeFeatureRequired, _MoleculeFeatureOptional):
    pass

#: The molecular-scale view layers. Composable — the renderer draws every enabled layer.
_MoleculeRepresentationRequired = TypedDict("_MoleculeRepresentationRequired", {})
_MoleculeRepresentationOptional = TypedDict("_MoleculeRepresentationOptional", {"bonds": Literal["none", "wire", "ball-stick", "spacefill"], "electron": Literal["none", "cloud"], "nucleus": Literal["none", "nuclei"]}, total=False)
class MoleculeRepresentation(_MoleculeRepresentationRequired, _MoleculeRepresentationOptional):
    pass

#: The NURBS half of a curve — degree, knots, weights. Stored verbatim as a sketch spline's `nurbs`.
_NurbsSpecRequired = TypedDict("_NurbsSpecRequired", {"degree": float})
_NurbsSpecOptional = TypedDict("_NurbsSpecOptional", {"weights": List[float], "knots": List[float], "mults": List[float], "periodic": bool}, total=False)
class NurbsSpec(_NurbsSpecRequired, _NurbsSpecOptional):
    pass

_OffsetFacesFeatureRequired = TypedDict("_OffsetFacesFeatureRequired", {"type": Literal["offsetFaces"], "faces": List['TopoRef'], "distance": float, "id": str, "name": str})
_OffsetFacesFeatureOptional = TypedDict("_OffsetFacesFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class OffsetFacesFeature(_OffsetFacesFeatureRequired, _OffsetFacesFeatureOptional):
    pass

#: The rectangle of parameter space a chart occupies. Half-open in the periodic direction.
_ParamRectRequired = TypedDict("_ParamRectRequired", {"uMin": float, "uMax": float, "vMin": float, "vMax": float})
_ParamRectOptional = TypedDict("_ParamRectOptional", {}, total=False)
class ParamRect(_ParamRectRequired, _ParamRectOptional):
    pass

_PathPatternFeatureRequired = TypedDict("_PathPatternFeatureRequired", {"type": Literal["pathPattern"], "seedFeature": str, "path": 'ProfileRef', "count": int, "id": str, "name": str})
_PathPatternFeatureOptional = TypedDict("_PathPatternFeatureOptional", {"alignToPath": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class PathPatternFeature(_PathPatternFeatureRequired, _PathPatternFeatureOptional):
    pass

#: A PCB TRACE — the 2D→3D rung. Points → route → centreline → offset → region → extrude.
_PcbTraceFeatureRequired = TypedDict("_PcbTraceFeatureRequired", {"type": Literal["pcbTrace"], "path": 'ConductorPathRef', "layer": 'CopperLayerRef', "rule": 'RoutingRule', "width": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str, "name": str})
_PcbTraceFeatureOptional = TypedDict("_PcbTraceFeatureOptional", {"centreline": Literal["arc-through-three-points"], "bias": 'RouteBias', "join": 'OffsetJoin', "cap": 'OffsetCap', "material": 'MaterialDef', "bindings": List['TerminalBinding'], "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class PcbTraceFeature(_PcbTraceFeatureRequired, _PcbTraceFeatureOptional):
    pass

#: A rigid placement of a part in assembly space: a position, an orientation quaternion, and a uniform scale. Mirrors import but is self-contained (no pivot — the part is placed about its own origin) so the pure model has no kernel dependency.
_PlacementRequired = TypedDict("_PlacementRequired", {"position": 'Vec3', "quaternion": Tuple[float, float, float, float], "scale": float})
_PlacementOptional = TypedDict("_PlacementOptional", {"scaleXYZ": 'Vec3'}, total=False)
class Placement(_PlacementRequired, _PlacementOptional):
    pass

#: A plane: `S(u,v) = origin + u·xAxis + v·yAxis`. Parameters are LENGTHS. K ≡ 0.
_PlanarSurfaceRequired = TypedDict("_PlanarSurfaceRequired", {"kind": Literal["plane"], "origin": 'Vec3', "xAxis": 'Vec3', "yAxis": 'Vec3', "axis": 'Vec3'})
_PlanarSurfaceOptional = TypedDict("_PlanarSurfaceOptional", {}, total=False)
class PlanarSurface(_PlanarSurfaceRequired, _PlanarSurfaceOptional):
    pass

__PlaneRef15Required = TypedDict("__PlaneRef15Required", {"type": Literal["datum"], "plane": str})
__PlaneRef15Optional = TypedDict("__PlaneRef15Optional", {}, total=False)
class _PlaneRef15(__PlaneRef15Required, __PlaneRef15Optional):
    pass

__PlaneRef16Required = TypedDict("__PlaneRef16Required", {"type": Literal["face"], "ref": 'TopoRef'})
__PlaneRef16Optional = TypedDict("__PlaneRef16Optional", {}, total=False)
class _PlaneRef16(__PlaneRef16Required, __PlaneRef16Optional):
    pass

__PlaneRef17Required = TypedDict("__PlaneRef17Required", {"type": Literal["unwrap"], "domain": 'UnwrapDomain'})
__PlaneRef17Optional = TypedDict("__PlaneRef17Optional", {}, total=False)
class _PlaneRef17(__PlaneRef17Required, __PlaneRef17Optional):
    pass

#: A PLATED through-hole — a terminal producer, and a DIFFERENT NODE from the mechanical `hole` it is routinely confused with.
_PlatedHoleFeatureRequired = TypedDict("_PlatedHoleFeatureRequired", {"type": Literal["platedHole"], "at": 'ConductorPathRef', "layers": List['CopperLayerRef'], "drillMm": float, "padDiameterMm": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str, "name": str})
_PlatedHoleFeatureOptional = TypedDict("_PlatedHoleFeatureOptional", {"material": 'MaterialDef', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class PlatedHoleFeature(_PlatedHoleFeatureRequired, _PlatedHoleFeatureOptional):
    pass

__PointCloudFeature18Required = TypedDict("__PointCloudFeature18Required", {})
__PointCloudFeature18Optional = TypedDict("__PointCloudFeature18Optional", {"format": str, "fileId": str, "fileName": str}, total=False)
class _PointCloudFeature18(__PointCloudFeature18Required, __PointCloudFeature18Optional):
    pass

#: A raw point cloud — scan points, SWC point sets, or a splat stripped of covariance.
_PointCloudFeatureRequired = TypedDict("_PointCloudFeatureRequired", {"type": Literal["pointCloud"], "positions": List[float], "id": str, "name": str})
_PointCloudFeatureOptional = TypedDict("_PointCloudFeatureOptional", {"colors": List[float], "pointSize": float, "source": '_PointCloudFeature18', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class PointCloudFeature(_PointCloudFeatureRequired, _PointCloudFeatureOptional):
    pass

#: A profile drawn from a sketch's solved closed regions.
_ProfileRefRequired = TypedDict("_ProfileRefRequired", {"sketch": str})
_ProfileRefOptional = TypedDict("_ProfileRefOptional", {"regions": List[float]}, total=False)
class ProfileRef(_ProfileRefRequired, _ProfileRefOptional):
    pass

_RevolveFeatureRequired = TypedDict("_RevolveFeatureRequired", {"type": Literal["revolve"], "profile": 'ProfileRef', "axis": 'AxisRef', "angle": float, "operation": 'BooleanMode', "id": str, "name": str})
_RevolveFeatureOptional = TypedDict("_RevolveFeatureOptional", {"reverse": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class RevolveFeature(_RevolveFeatureRequired, _RevolveFeatureOptional):
    pass

_RibFeatureRequired = TypedDict("_RibFeatureRequired", {"type": Literal["rib"], "sketch": str, "thickness": float, "depth": float, "operation": 'BooleanMode', "id": str, "name": str})
_RibFeatureOptional = TypedDict("_RibFeatureOptional", {"bothSides": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class RibFeature(_RibFeatureRequired, _RibFeatureOptional):
    pass

_ScaleFeatureRequired = TypedDict("_ScaleFeatureRequired", {"type": Literal["scale"], "factor": float, "id": str, "name": str})
_ScaleFeatureOptional = TypedDict("_ScaleFeatureOptional", {"center": 'Vec3', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ScaleFeature(_ScaleFeatureRequired, _ScaleFeatureOptional):
    pass

_SheetFlangeFeatureRequired = TypedDict("_SheetFlangeFeatureRequired", {"type": Literal["sheetFlange"], "edge": 'TopoRef', "length": float, "angle": float, "id": str, "name": str})
_SheetFlangeFeatureOptional = TypedDict("_SheetFlangeFeatureOptional", {"thickness": float, "bendRadius": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SheetFlangeFeature(_SheetFlangeFeatureRequired, _SheetFlangeFeatureOptional):
    pass

_ShellFeatureRequired = TypedDict("_ShellFeatureRequired", {"type": Literal["shell"], "faces": List['TopoRef'], "thickness": float, "id": str, "name": str})
_ShellFeatureOptional = TypedDict("_ShellFeatureOptional", {"outward": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ShellFeature(_ShellFeatureRequired, _ShellFeatureOptional):
    pass

__SkeletonFeature19Required = TypedDict("__SkeletonFeature19Required", {})
__SkeletonFeature19Optional = TypedDict("__SkeletonFeature19Optional", {"format": str, "fileId": str, "fileName": str}, total=False)
class _SkeletonFeature19(__SkeletonFeature19Required, __SkeletonFeature19Optional):
    pass

#: A **skeleton** — a tree/graph of nodes with radii, the native representation for neuronal & vascular morphology (SWC: soma/axon/dendrite trees) and connectome traces. Rendered as radius-varying tubes.
_SkeletonFeatureRequired = TypedDict("_SkeletonFeatureRequired", {"type": Literal["skeleton"], "positions": List[float], "parents": List[float], "id": str, "name": str})
_SkeletonFeatureOptional = TypedDict("_SkeletonFeatureOptional", {"radii": List[float], "nodeTypes": List[float], "source": '_SkeletonFeature19', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SkeletonFeature(_SkeletonFeatureRequired, _SkeletonFeatureOptional):
    pass

_SketchRequired = TypedDict("_SketchRequired", {"points": Dict[str, 'SketchPoint'], "segments": Dict[str, 'SketchSegment'], "constraints": Dict[str, 'SketchConstraint'], "pointOrder": List[str], "segmentOrder": List[str], "constraintOrder": List[str]})
_SketchOptional = TypedDict("_SketchOptional", {"projections": Dict[str, 'SketchProjection'], "projectionOrder": List[str], "solveStatus": 'SketchSolveStatus', "dof": float}, total=False)
class Sketch(_SketchRequired, _SketchOptional):
    pass

#: A constraint references entities by id. `entities` holds point/segment ids in the order the kind's `operands` declare (`../geometry/constraints.ts`); `value` holds the dimension for dimensional kinds (distance in the sketch's length unit, angle in radians, radius in the length unit).
_SketchConstraintRequired = TypedDict("_SketchConstraintRequired", {"id": str, "kind": 'ConstraintKind', "entities": List[str]})
_SketchConstraintOptional = TypedDict("_SketchConstraintOptional", {"value": float, "reference": bool}, total=False)
class SketchConstraint(_SketchConstraintRequired, _SketchConstraintOptional):
    pass

_SketchFeatureRequired = TypedDict("_SketchFeatureRequired", {"type": Literal["sketch"], "plane": 'PlaneRef', "sketch": 'Sketch', "id": str, "name": str})
_SketchFeatureOptional = TypedDict("_SketchFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SketchFeature(_SketchFeatureRequired, _SketchFeatureOptional):
    pass

_SketchPinRequired = TypedDict("_SketchPinRequired", {"target": 'SketchPinTarget', "anchor": 'SketchPinAnchor'})
_SketchPinOptional = TypedDict("_SketchPinOptional", {"offset": Tuple[float, float], "label": str}, total=False)
class SketchPin(_SketchPinRequired, _SketchPinOptional):
    pass

__SketchPinTarget20Required = TypedDict("__SketchPinTarget20Required", {"kind": Literal["body"], "feature": str})
__SketchPinTarget20Optional = TypedDict("__SketchPinTarget20Optional", {}, total=False)
class _SketchPinTarget20(__SketchPinTarget20Required, __SketchPinTarget20Optional):
    pass

__SketchPinTarget21Required = TypedDict("__SketchPinTarget21Required", {"kind": Literal["face"], "ref": 'TopoRef'})
__SketchPinTarget21Optional = TypedDict("__SketchPinTarget21Optional", {}, total=False)
class _SketchPinTarget21(__SketchPinTarget21Required, __SketchPinTarget21Optional):
    pass

__SketchPinTarget22Required = TypedDict("__SketchPinTarget22Required", {"kind": Literal["edge"], "ref": 'TopoRef'})
__SketchPinTarget22Optional = TypedDict("__SketchPinTarget22Optional", {}, total=False)
class _SketchPinTarget22(__SketchPinTarget22Required, __SketchPinTarget22Optional):
    pass

__SketchPinTarget23Required = TypedDict("__SketchPinTarget23Required", {"kind": Literal["vertex"], "ref": 'TopoRef'})
__SketchPinTarget23Optional = TypedDict("__SketchPinTarget23Optional", {}, total=False)
class _SketchPinTarget23(__SketchPinTarget23Required, __SketchPinTarget23Optional):
    pass

__SketchPinTarget24Required = TypedDict("__SketchPinTarget24Required", {"kind": Literal["pad"], "pad": str, "producer": str})
__SketchPinTarget24Optional = TypedDict("__SketchPinTarget24Optional", {}, total=False)
class _SketchPinTarget24(__SketchPinTarget24Required, __SketchPinTarget24Optional):
    pass

_SketchPointRequired = TypedDict("_SketchPointRequired", {"id": str, "x": float, "y": float})
_SketchPointOptional = TypedDict("_SketchPointOptional", {"pin": 'SketchPin', "construction": bool, "fixed": bool, "from": str}, total=False)
class SketchPoint(_SketchPointRequired, _SketchPointOptional):
    pass

#: A LIVE PROJECTION of one model edge onto this sketch's plane — "use that hole's circle here".
_SketchProjectionRequired = TypedDict("_SketchProjectionRequired", {"id": str, "ref": 'TopoRef'})
_SketchProjectionOptional = TypedDict("_SketchProjectionOptional", {"feature": str, "construction": bool, "label": str}, total=False)
class SketchProjection(_SketchProjectionRequired, _SketchProjectionOptional):
    pass

__SketchSegment25Required = TypedDict("__SketchSegment25Required", {"id": str, "type": Literal["line"], "a": str, "b": str})
__SketchSegment25Optional = TypedDict("__SketchSegment25Optional", {"construction": bool, "from": str}, total=False)
class _SketchSegment25(__SketchSegment25Required, __SketchSegment25Optional):
    pass

__SketchSegment26Required = TypedDict("__SketchSegment26Required", {"id": str, "type": Literal["circle"], "center": str, "radius": float})
__SketchSegment26Optional = TypedDict("__SketchSegment26Optional", {"construction": bool, "from": str}, total=False)
class _SketchSegment26(__SketchSegment26Required, __SketchSegment26Optional):
    pass

__SketchSegment27Required = TypedDict("__SketchSegment27Required", {"id": str, "type": Literal["arc"], "center": str, "start": str, "end": str, "radius": float})
__SketchSegment27Optional = TypedDict("__SketchSegment27Optional", {"construction": bool, "from": str}, total=False)
class _SketchSegment27(__SketchSegment27Required, __SketchSegment27Optional):
    pass

__SketchSegment28Required = TypedDict("__SketchSegment28Required", {"id": str, "type": Literal["spline"], "points": List[str]})
__SketchSegment28Optional = TypedDict("__SketchSegment28Optional", {"closed": bool, "construction": bool, "nurbs": 'NurbsSpec', "from": str}, total=False)
class _SketchSegment28(__SketchSegment28Required, __SketchSegment28Optional):
    pass

__SketchSegment29Required = TypedDict("__SketchSegment29Required", {"id": str, "type": Literal["ellipse"], "center": str, "focus": str, "minorRadius": float})
__SketchSegment29Optional = TypedDict("__SketchSegment29Optional", {"construction": bool, "from": str}, total=False)
class _SketchSegment29(__SketchSegment29Required, __SketchSegment29Optional):
    pass

__SketchSegment30Required = TypedDict("__SketchSegment30Required", {"id": str, "type": Literal["ellipseArc"], "center": str, "focus": str, "minorRadius": float, "start": str, "end": str})
__SketchSegment30Optional = TypedDict("__SketchSegment30Optional", {"construction": bool, "from": str}, total=False)
class _SketchSegment30(__SketchSegment30Required, __SketchSegment30Optional):
    pass

__SourceCompressedTexture31Required = TypedDict("__SourceCompressedTexture31Required", {"width": float, "height": float, "data": str})
__SourceCompressedTexture31Optional = TypedDict("__SourceCompressedTexture31Optional", {}, total=False)
class _SourceCompressedTexture31(__SourceCompressedTexture31Required, __SourceCompressedTexture31Optional):
    pass

#: GPU-compressed mip payload retained from KTX2 decoding.
_SourceCompressedTextureRequired = TypedDict("_SourceCompressedTextureRequired", {"kind": Literal["compressed"], "width": float, "height": float, "format": float, "type": float, "mipmaps": List['_SourceCompressedTexture31']})
_SourceCompressedTextureOptional = TypedDict("_SourceCompressedTextureOptional", {"name": str, "colorSpace": str, "channel": float, "wrapS": float, "wrapT": float, "magFilter": float, "minFilter": float, "anisotropy": float, "flipY": bool, "transform": 'SourceTextureTransform'}, total=False)
class SourceCompressedTexture(_SourceCompressedTextureRequired, _SourceCompressedTextureOptional):
    pass

#: Universal uncompressed pixel data (for DataTexture and legacy Basis RGBA output).
_SourceDataTextureRequired = TypedDict("_SourceDataTextureRequired", {"kind": Literal["data"], "width": float, "height": float, "data": str, "format": float, "type": float})
_SourceDataTextureOptional = TypedDict("_SourceDataTextureOptional", {"name": str, "colorSpace": str, "channel": float, "wrapS": float, "wrapT": float, "magFilter": float, "minFilter": float, "anisotropy": float, "flipY": bool, "transform": 'SourceTextureTransform'}, total=False)
class SourceDataTexture(_SourceDataTextureRequired, _SourceDataTextureOptional):
    pass

#: Browser-decodable PNG/JPEG/WebP/etc bytes, kept as a data URL until bundle hoisting.
_SourceImageTextureRequired = TypedDict("_SourceImageTextureRequired", {"kind": Literal["image"], "data": str})
_SourceImageTextureOptional = TypedDict("_SourceImageTextureOptional", {"name": str, "colorSpace": str, "channel": float, "wrapS": float, "wrapT": float, "magFilter": float, "minFilter": float, "anisotropy": float, "flipY": bool, "transform": 'SourceTextureTransform'}, total=False)
class SourceImageTexture(_SourceImageTextureRequired, _SourceImageTextureOptional):
    pass

__SourceMaterial32Required = TypedDict("__SourceMaterial32Required", {})
__SourceMaterial32Optional = TypedDict("__SourceMaterial32Optional", {"map": 'SourceTexture', "normalMap": 'SourceTexture', "roughnessMap": 'SourceTexture', "metalnessMap": 'SourceTexture', "aoMap": 'SourceTexture', "emissiveMap": 'SourceTexture', "alphaMap": 'SourceTexture', "bumpMap": 'SourceTexture', "displacementMap": 'SourceTexture', "specularMap": 'SourceTexture', "specularColorMap": 'SourceTexture', "clearcoatMap": 'SourceTexture', "clearcoatNormalMap": 'SourceTexture', "clearcoatRoughnessMap": 'SourceTexture'}, total=False)
class _SourceMaterial32(__SourceMaterial32Required, __SourceMaterial32Optional):
    pass

_SourceMaterialRequired = TypedDict("_SourceMaterialRequired", {"kind": Literal["basic", "phong", "standard", "physical"]})
_SourceMaterialOptional = TypedDict("_SourceMaterialOptional", {"name": str, "color": str, "emissive": str, "metalness": float, "roughness": float, "opacity": float, "transparent": bool, "alphaTest": float, "side": float, "flatShading": bool, "depthWrite": bool, "vertexColors": bool, "ior": float, "clearcoat": float, "clearcoatRoughness": float, "specularIntensity": float, "shininess": float, "bumpScale": float, "displacementScale": float, "normalScale": Tuple[float, float], "textures": '_SourceMaterial32'}, total=False)
class SourceMaterial(_SourceMaterialRequired, _SourceMaterialOptional):
    pass

_SourceMaterialGroupRequired = TypedDict("_SourceMaterialGroupRequired", {"start": float, "count": float, "materialIndex": float})
_SourceMaterialGroupOptional = TypedDict("_SourceMaterialGroupOptional", {}, total=False)
class SourceMaterialGroup(_SourceMaterialGroupRequired, _SourceMaterialGroupOptional):
    pass

_SourceTextureTransformRequired = TypedDict("_SourceTextureTransformRequired", {"offset": Tuple[float, float], "repeat": Tuple[float, float], "center": Tuple[float, float], "rotation": float, "matrixAutoUpdate": bool})
_SourceTextureTransformOptional = TypedDict("_SourceTextureTransformOptional", {}, total=False)
class SourceTextureTransform(_SourceTextureTransformRequired, _SourceTextureTransformOptional):
    pass

_SphereFeatureRequired = TypedDict("_SphereFeatureRequired", {"type": Literal["sphere"], "center": 'Vec3', "radius": float, "operation": 'BooleanMode', "id": str, "name": str})
_SphereFeatureOptional = TypedDict("_SphereFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SphereFeature(_SphereFeatureRequired, _SphereFeatureOptional):
    pass

#: A sphere: `S(u,v) = origin + R(cos v·cos u·x + cos v·sin u·y + sin v·axis)`. K = 1/R².
_SphericalSurfaceRequired = TypedDict("_SphericalSurfaceRequired", {"kind": Literal["sphere"], "radius": float, "origin": 'Vec3', "xAxis": 'Vec3', "yAxis": 'Vec3', "axis": 'Vec3'})
_SphericalSurfaceOptional = TypedDict("_SphericalSurfaceOptional", {}, total=False)
class SphericalSurface(_SphericalSurfaceRequired, _SphericalSurfaceOptional):
    pass

_SplitFeatureRequired = TypedDict("_SplitFeatureRequired", {"type": Literal["split"], "plane": 'PlaneRef', "id": str, "name": str})
_SplitFeatureOptional = TypedDict("_SplitFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SplitFeature(_SplitFeatureRequired, _SplitFeatureOptional):
    pass

#: A subdivision-surface body (Catmull-Clark). Authored in the **sculpt** mode as an editable control cage — a quad mesh you push/pull/subdivide — and committed into the document as a body. The cage is stored verbatim (control points + quad faces); the surface is computed by subdividing `level` times (pure TS subdivision in `cad/model/subdiv.ts`), then meshed for display. Independent of the OCC kernel (which has no native subdivision), so it works everywhere.
_SubdivBodyFeatureRequired = TypedDict("_SubdivBodyFeatureRequired", {"type": Literal["subdivBody"], "controlPoints": List['Vec3'], "faces": List[List[float]], "level": float, "id": str, "name": str})
_SubdivBodyFeatureOptional = TypedDict("_SubdivBodyFeatureOptional", {"operation": 'BooleanMode', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SubdivBodyFeature(_SubdivBodyFeatureRequired, _SubdivBodyFeatureOptional):
    pass

_SweepFeatureRequired = TypedDict("_SweepFeatureRequired", {"type": Literal["sweep"], "profile": 'ProfileRef', "path": 'ProfileRef', "operation": 'BooleanMode', "id": str, "name": str})
_SweepFeatureOptional = TypedDict("_SweepFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class SweepFeature(_SweepFeatureRequired, _SweepFeatureOptional):
    pass

#: A BINDING: this conductor is electrically joined to that pad. L3, and L2.
_TerminalBindingRequired = TypedDict("_TerminalBindingRequired", {"point": str, "pad": str})
_TerminalBindingOptional = TypedDict("_TerminalBindingOptional", {}, total=False)
class TerminalBinding(_TerminalBindingRequired, _TerminalBindingOptional):
    pass

_ThickenFeatureRequired = TypedDict("_ThickenFeatureRequired", {"type": Literal["thicken"], "distance": float, "id": str, "name": str})
_ThickenFeatureOptional = TypedDict("_ThickenFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ThickenFeature(_ThickenFeatureRequired, _ThickenFeatureOptional):
    pass

_ThreadFeatureRequired = TypedDict("_ThreadFeatureRequired", {"type": Literal["thread"], "face": 'TopoRef', "pitch": float, "length": float, "depth": float, "id": str, "name": str})
_ThreadFeatureOptional = TypedDict("_ThreadFeatureOptional", {"internal": bool, "rightHanded": bool, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class ThreadFeature(_ThreadFeatureRequired, _ThreadFeatureOptional):
    pass

_TopoRefRequired = TypedDict("_TopoRefRequired", {"kind": Literal["face", "edge", "vertex"], "signature": 'TopoSignature'})
_TopoRefOptional = TypedDict("_TopoRefOptional", {"feature": str, "label": str}, total=False)
class TopoRef(_TopoRefRequired, _TopoRefOptional):
    pass

_TopoSignatureRequired = TypedDict("_TopoSignatureRequired", {"point": 'Vec3'})
_TopoSignatureOptional = TypedDict("_TopoSignatureOptional", {"normal": 'Vec3', "area": float, "length": float, "dir": 'Vec3'}, total=False)
class TopoSignature(_TopoSignatureRequired, _TopoSignatureOptional):
    pass

#: A torus: `S(u,v) = origin + (Rmaj + Rmin·cos v)(cos u·x + sin u·y) + Rmin·sin v·axis`. K = cos v / (Rmin(Rmaj + Rmin·cos v)) — it CHANGES SIGN across the tube, which makes it the sharpest doubly-curved control: no single scalar can describe its distortion.
_ToroidalSurfaceRequired = TypedDict("_ToroidalSurfaceRequired", {"kind": Literal["torus"], "majorRadius": float, "minorRadius": float, "origin": 'Vec3', "xAxis": 'Vec3', "yAxis": 'Vec3', "axis": 'Vec3'})
_ToroidalSurfaceOptional = TypedDict("_ToroidalSurfaceOptional", {}, total=False)
class ToroidalSurface(_ToroidalSurfaceRequired, _ToroidalSurfaceOptional):
    pass

_TransformFeatureRequired = TypedDict("_TransformFeatureRequired", {"type": Literal["transform"], "seedFeature": str, "id": str, "name": str})
_TransformFeatureOptional = TypedDict("_TransformFeatureOptional", {"translate": 'Vec3', "rotateAxis": 'AxisRef', "rotateAngle": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class TransformFeature(_TransformFeatureRequired, _TransformFeatureOptional):
    pass

_UnfoldFeatureRequired = TypedDict("_UnfoldFeatureRequired", {"type": Literal["unfold"], "id": str, "name": str})
_UnfoldFeatureOptional = TypedDict("_UnfoldFeatureOptional", {"kFactor": float, "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class UnfoldFeature(_UnfoldFeatureRequired, _UnfoldFeatureOptional):
    pass

_UnwrapChartRequired = TypedDict("_UnwrapChartRequired", {"id": str, "surface": 'UnwrapSurface', "rect": 'ParamRect'})
_UnwrapChartOptional = TypedDict("_UnwrapChartOptional", {"source": 'TopoRef', "placement": 'ChartPlacement', "map": 'FittedChartMap'}, total=False)
class UnwrapChart(_UnwrapChartRequired, _UnwrapChartOptional):
    pass

__UnwrapDomain33Required = TypedDict("__UnwrapDomain33Required", {"chart": str, "residual": float, "tolerance": float})
__UnwrapDomain33Optional = TypedDict("__UnwrapDomain33Optional", {}, total=False)
class _UnwrapDomain33(__UnwrapDomain33Required, __UnwrapDomain33Optional):
    pass

_UnwrapDomainRequired = TypedDict("_UnwrapDomainRequired", {"id": str, "charts": List['UnwrapChart'], "anchor": str, "stitches": List['UnwrapIdentification'], "seams": List['UnwrapIdentification'], "isometric": bool, "developability": List['DevelopabilityVerdict'], "distortion": List['ChartDistortionSummary'], "fits": List['_UnwrapDomain33'], "bindTolerance": float, "resolution": float})
_UnwrapDomainOptional = TypedDict("_UnwrapDomainOptional", {}, total=False)
class UnwrapDomain(_UnwrapDomainRequired, _UnwrapDomainOptional):
    pass

__UnwrapIdentification34Required = TypedDict("__UnwrapIdentification34Required", {"chart": str, "edge": 'ChartEdge'})
__UnwrapIdentification34Optional = TypedDict("__UnwrapIdentification34Optional", {}, total=False)
class _UnwrapIdentification34(__UnwrapIdentification34Required, __UnwrapIdentification34Optional):
    pass

__UnwrapIdentification35Required = TypedDict("__UnwrapIdentification35Required", {"chart": str, "edge": 'ChartEdge'})
__UnwrapIdentification35Optional = TypedDict("__UnwrapIdentification35Optional", {}, total=False)
class _UnwrapIdentification35(__UnwrapIdentification35Required, __UnwrapIdentification35Optional):
    pass

#: "These two chart edges are the same curve on the part." The atlas's only authored relation.
_UnwrapIdentificationRequired = TypedDict("_UnwrapIdentificationRequired", {"id": str, "a": '_UnwrapIdentification34', "b": '_UnwrapIdentification35'})
_UnwrapIdentificationOptional = TypedDict("_UnwrapIdentificationOptional", {"label": str}, total=False)
class UnwrapIdentification(_UnwrapIdentificationRequired, _UnwrapIdentificationOptional):
    pass

__VolumeFeature36Required = TypedDict("__VolumeFeature36Required", {})
__VolumeFeature36Optional = TypedDict("__VolumeFeature36Optional", {"format": str, "fileId": str, "fileName": str, "kind": Literal["scalar", "label"]}, total=False)
class _VolumeFeature36(__VolumeFeature36Required, __VolumeFeature36Optional):
    pass

#: A **scalar/label voxel volume** — CT/MRI/microscopy/segmentation grids (NIfTI/NRRD/DICOM). The field is normalized 0..1 and downsampled to a display-friendly grid on import (large clinical volumes don't fit a JSON doc verbatim). Rendered as three orthogonal MPR slice planes or a marching-cubes isosurface.
_VolumeFeatureRequired = TypedDict("_VolumeFeatureRequired", {"type": Literal["volume"], "dims": Tuple[float, float, float], "spacing": Tuple[float, float, float], "origin": 'Vec3', "data": List[float], "id": str, "name": str})
_VolumeFeatureOptional = TypedDict("_VolumeFeatureOptional", {"render": Literal["slices", "iso"], "iso": float, "colormap": str, "source": '_VolumeFeature36', "suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class VolumeFeature(_VolumeFeatureRequired, _VolumeFeatureOptional):
    pass

_WrapTextFeatureRequired = TypedDict("_WrapTextFeatureRequired", {"type": Literal["wrapText"], "face": 'TopoRef', "sketch": 'Sketch', "depth": float, "mode": Literal["emboss", "engrave"], "id": str, "name": str})
_WrapTextFeatureOptional = TypedDict("_WrapTextFeatureOptional", {"suppressed": bool, "error": str, "consumes": List[str], "declaredBy": 'CodeFeature'}, total=False)
class WrapTextFeature(_WrapTextFeatureRequired, _WrapTextFeatureOptional):
    pass

#: The keywords of code(…): the CodeFeature fields, in snake_case.
_CodePropsRequired = TypedDict("_CodePropsRequired", {"source": str, "id": str})
_CodePropsOptional = TypedDict("_CodePropsOptional", {"inputs": Dict[str, Any], "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CodeProps(_CodePropsRequired, _CodePropsOptional):
    pass

#: The keywords of sketch(…): the SketchFeature fields, in snake_case.
_SketchPropsRequired = TypedDict("_SketchPropsRequired", {"plane": 'PlaneRef', "id": str})
_SketchPropsOptional = TypedDict("_SketchPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SketchProps(_SketchPropsRequired, _SketchPropsOptional):
    pass

#: The keywords of extrude(…): the ExtrudeFeature fields, in snake_case.
_ExtrudePropsRequired = TypedDict("_ExtrudePropsRequired", {"profile": 'ProfileRef', "distance": float, "operation": 'BooleanMode', "id": str})
_ExtrudePropsOptional = TypedDict("_ExtrudePropsOptional", {"symmetric": bool, "reverse": bool, "distance2": float, "draft_angle": float, "through": bool, "up_to_face": 'TopoRef', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ExtrudeProps(_ExtrudePropsRequired, _ExtrudePropsOptional):
    pass

#: The keywords of revolve(…): the RevolveFeature fields, in snake_case.
_RevolvePropsRequired = TypedDict("_RevolvePropsRequired", {"profile": 'ProfileRef', "axis": 'AxisRef', "angle": float, "operation": 'BooleanMode', "id": str})
_RevolvePropsOptional = TypedDict("_RevolvePropsOptional", {"reverse": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class RevolveProps(_RevolvePropsRequired, _RevolvePropsOptional):
    pass

#: The keywords of sweep(…): the SweepFeature fields, in snake_case.
_SweepPropsRequired = TypedDict("_SweepPropsRequired", {"profile": 'ProfileRef', "path": 'ProfileRef', "operation": 'BooleanMode', "id": str})
_SweepPropsOptional = TypedDict("_SweepPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SweepProps(_SweepPropsRequired, _SweepPropsOptional):
    pass

#: The keywords of loft(…): the LoftFeature fields, in snake_case.
_LoftPropsRequired = TypedDict("_LoftPropsRequired", {"profiles": List['ProfileRef'], "operation": 'BooleanMode', "id": str})
_LoftPropsOptional = TypedDict("_LoftPropsOptional", {"ruled": bool, "closed": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class LoftProps(_LoftPropsRequired, _LoftPropsOptional):
    pass

#: The keywords of fillet(…): the FilletFeature fields, in snake_case.
_FilletPropsRequired = TypedDict("_FilletPropsRequired", {"edges": List['TopoRef'], "radius": float, "id": str})
_FilletPropsOptional = TypedDict("_FilletPropsOptional", {"radius2": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class FilletProps(_FilletPropsRequired, _FilletPropsOptional):
    pass

#: The keywords of chamfer(…): the ChamferFeature fields, in snake_case.
_ChamferPropsRequired = TypedDict("_ChamferPropsRequired", {"edges": List['TopoRef'], "distance": float, "id": str})
_ChamferPropsOptional = TypedDict("_ChamferPropsOptional", {"distance2": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ChamferProps(_ChamferPropsRequired, _ChamferPropsOptional):
    pass

#: The keywords of shell(…): the ShellFeature fields, in snake_case.
_ShellPropsRequired = TypedDict("_ShellPropsRequired", {"faces": List['TopoRef'], "thickness": float, "id": str})
_ShellPropsOptional = TypedDict("_ShellPropsOptional", {"outward": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ShellProps(_ShellPropsRequired, _ShellPropsOptional):
    pass

#: The keywords of box(…): the BoxFeature fields, in snake_case.
_BoxPropsRequired = TypedDict("_BoxPropsRequired", {"center": 'Vec3', "size": 'Vec3', "operation": 'BooleanMode', "id": str})
_BoxPropsOptional = TypedDict("_BoxPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class BoxProps(_BoxPropsRequired, _BoxPropsOptional):
    pass

#: The keywords of import(…): the ImportFeature fields, in snake_case.
_ImportPropsRequired = TypedDict("_ImportPropsRequired", {"format": Literal["step", "iges"], "data": str, "operation": 'BooleanMode', "id": str})
_ImportPropsOptional = TypedDict("_ImportPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ImportProps(_ImportPropsRequired, _ImportPropsOptional):
    pass

#: The keywords of externalPart(…): the ExternalPartRef fields, in snake_case.
_ExternalPartPropsRequired = TypedDict("_ExternalPartPropsRequired", {"placement": 'Placement', "operation": 'BooleanMode', "id": str})
_ExternalPartPropsOptional = TypedDict("_ExternalPartPropsOptional", {"file_id": str, "path": str, "file_name": str, "importer": Literal["step", "iges", "3d", "wrl", "glb", "gltf", "obj", "stl", "ply", "3mf", "fbx", "dae", "usd", "kicad_pcb", "pcb.tsx"], "unit_scale_mm": float, "component": str, "local_placement": 'Placement', "footprint": 'ComponentFootprint', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ExternalPartProps(_ExternalPartPropsRequired, _ExternalPartPropsOptional):
    pass

#: The keywords of cylinder(…): the CylinderFeature fields, in snake_case.
_CylinderPropsRequired = TypedDict("_CylinderPropsRequired", {"center": 'Vec3', "axis": 'Vec3', "radius": float, "height": float, "operation": 'BooleanMode', "id": str})
_CylinderPropsOptional = TypedDict("_CylinderPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CylinderProps(_CylinderPropsRequired, _CylinderPropsOptional):
    pass

#: The keywords of sphere(…): the SphereFeature fields, in snake_case.
_SpherePropsRequired = TypedDict("_SpherePropsRequired", {"center": 'Vec3', "radius": float, "operation": 'BooleanMode', "id": str})
_SpherePropsOptional = TypedDict("_SpherePropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SphereProps(_SpherePropsRequired, _SpherePropsOptional):
    pass

#: The keywords of cone(…): the ConeFeature fields, in snake_case.
_ConePropsRequired = TypedDict("_ConePropsRequired", {"center": 'Vec3', "axis": 'Vec3', "radius1": float, "radius2": float, "height": float, "operation": 'BooleanMode', "id": str})
_ConePropsOptional = TypedDict("_ConePropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ConeProps(_ConePropsRequired, _ConePropsOptional):
    pass

#: The keywords of makeHuman(…): the MakeHumanFeature fields, in snake_case.
_MakeHumanPropsRequired = TypedDict("_MakeHumanPropsRequired", {"id": str, "gender": float, "age": float, "muscle": float, "weight": float, "height": float, "proportions": float, "cupsize": float, "firmness": float, "african": float, "asian": float, "caucasian": float})
_MakeHumanPropsOptional = TypedDict("_MakeHumanPropsOptional", {"subdivision": int, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class MakeHumanProps(_MakeHumanPropsRequired, _MakeHumanPropsOptional):
    pass

#: The keywords of linearPattern(…): the LinearPatternFeature fields, in snake_case.
_LinearPatternPropsRequired = TypedDict("_LinearPatternPropsRequired", {"seed_feature": str, "direction": 'Vec3', "spacing": float, "count": int, "id": str})
_LinearPatternPropsOptional = TypedDict("_LinearPatternPropsOptional", {"direction2": 'Vec3', "spacing2": float, "count2": int, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class LinearPatternProps(_LinearPatternPropsRequired, _LinearPatternPropsOptional):
    pass

#: The keywords of circularPattern(…): the CircularPatternFeature fields, in snake_case.
_CircularPatternPropsRequired = TypedDict("_CircularPatternPropsRequired", {"seed_feature": str, "axis": 'AxisRef', "count": int, "id": str})
_CircularPatternPropsOptional = TypedDict("_CircularPatternPropsOptional", {"angle": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CircularPatternProps(_CircularPatternPropsRequired, _CircularPatternPropsOptional):
    pass

#: The keywords of pathPattern(…): the PathPatternFeature fields, in snake_case.
_PathPatternPropsRequired = TypedDict("_PathPatternPropsRequired", {"seed_feature": str, "path": 'ProfileRef', "count": int, "id": str})
_PathPatternPropsOptional = TypedDict("_PathPatternPropsOptional", {"align_to_path": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class PathPatternProps(_PathPatternPropsRequired, _PathPatternPropsOptional):
    pass

#: The keywords of mirror(…): the MirrorFeature fields, in snake_case.
_MirrorPropsRequired = TypedDict("_MirrorPropsRequired", {"plane": 'PlaneRef', "id": str})
_MirrorPropsOptional = TypedDict("_MirrorPropsOptional", {"seed_feature": str, "keep_original": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class MirrorProps(_MirrorPropsRequired, _MirrorPropsOptional):
    pass

#: The keywords of datumPlane(…): the DatumPlaneFeature fields, in snake_case.
_DatumPlanePropsRequired = TypedDict("_DatumPlanePropsRequired", {"base": str, "offset": float, "id": str})
_DatumPlanePropsOptional = TypedDict("_DatumPlanePropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class DatumPlaneProps(_DatumPlanePropsRequired, _DatumPlanePropsOptional):
    pass

#: The keywords of draft(…): the DraftFeature fields, in snake_case.
_DraftPropsRequired = TypedDict("_DraftPropsRequired", {"faces": List['TopoRef'], "angle": float, "pull_direction": 'Vec3', "id": str})
_DraftPropsOptional = TypedDict("_DraftPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class DraftProps(_DraftPropsRequired, _DraftPropsOptional):
    pass

#: The keywords of hole(…): the HoleFeature fields, in snake_case.
_HolePropsRequired = TypedDict("_HolePropsRequired", {"face": 'TopoRef', "diameter": float, "depth": float, "style": 'HoleStyle', "id": str})
_HolePropsOptional = TypedDict("_HolePropsOptional", {"through": bool, "head_diameter": float, "head_depth": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class HoleProps(_HolePropsRequired, _HolePropsOptional):
    pass

#: The keywords of transform(…): the TransformFeature fields, in snake_case.
_TransformPropsRequired = TypedDict("_TransformPropsRequired", {"seed_feature": str, "id": str})
_TransformPropsOptional = TypedDict("_TransformPropsOptional", {"translate": 'Vec3', "rotate_axis": 'AxisRef', "rotate_angle": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class TransformProps(_TransformPropsRequired, _TransformPropsOptional):
    pass

#: The keywords of sheetFlange(…): the SheetFlangeFeature fields, in snake_case.
_SheetFlangePropsRequired = TypedDict("_SheetFlangePropsRequired", {"edge": 'TopoRef', "length": float, "angle": float, "id": str})
_SheetFlangePropsOptional = TypedDict("_SheetFlangePropsOptional", {"thickness": float, "bend_radius": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SheetFlangeProps(_SheetFlangePropsRequired, _SheetFlangePropsOptional):
    pass

#: The keywords of unfold(…): the UnfoldFeature fields, in snake_case.
_UnfoldPropsRequired = TypedDict("_UnfoldPropsRequired", {"id": str})
_UnfoldPropsOptional = TypedDict("_UnfoldPropsOptional", {"k_factor": float, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class UnfoldProps(_UnfoldPropsRequired, _UnfoldPropsOptional):
    pass

#: The keywords of wrapText(…): the WrapTextFeature fields, in snake_case.
_WrapTextPropsRequired = TypedDict("_WrapTextPropsRequired", {"face": 'TopoRef', "sketch": 'Sketch', "depth": float, "mode": Literal["emboss", "engrave"], "id": str})
_WrapTextPropsOptional = TypedDict("_WrapTextPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class WrapTextProps(_WrapTextPropsRequired, _WrapTextPropsOptional):
    pass

#: The keywords of deleteFace(…): the DeleteFaceFeature fields, in snake_case.
_DeleteFacePropsRequired = TypedDict("_DeleteFacePropsRequired", {"faces": List['TopoRef'], "id": str})
_DeleteFacePropsOptional = TypedDict("_DeleteFacePropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class DeleteFaceProps(_DeleteFacePropsRequired, _DeleteFacePropsOptional):
    pass

#: The keywords of fullRound(…): the FullRoundFeature fields, in snake_case.
_FullRoundPropsRequired = TypedDict("_FullRoundPropsRequired", {"face": 'TopoRef', "id": str})
_FullRoundPropsOptional = TypedDict("_FullRoundPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class FullRoundProps(_FullRoundPropsRequired, _FullRoundPropsOptional):
    pass

#: The keywords of dome(…): the DomeFeature fields, in snake_case.
_DomePropsRequired = TypedDict("_DomePropsRequired", {"face": 'TopoRef', "height": float, "id": str})
_DomePropsOptional = TypedDict("_DomePropsOptional", {"rings": int, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class DomeProps(_DomePropsRequired, _DomePropsOptional):
    pass

#: The keywords of copyBody(…): the CopyBodyFeature fields, in snake_case.
_CopyBodyPropsRequired = TypedDict("_CopyBodyPropsRequired", {"body_id": str, "id": str})
_CopyBodyPropsOptional = TypedDict("_CopyBodyPropsOptional", {"translate": 'Vec3', "rotate_axis": 'AxisRef', "rotate_angle": float, "count": int, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CopyBodyProps(_CopyBodyPropsRequired, _CopyBodyPropsOptional):
    pass

#: The keywords of thread(…): the ThreadFeature fields, in snake_case.
_ThreadPropsRequired = TypedDict("_ThreadPropsRequired", {"face": 'TopoRef', "pitch": float, "length": float, "depth": float, "id": str})
_ThreadPropsOptional = TypedDict("_ThreadPropsOptional", {"internal": bool, "right_handed": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ThreadProps(_ThreadPropsRequired, _ThreadPropsOptional):
    pass

#: The keywords of coil(…): the CoilFeature fields, in snake_case.
_CoilPropsRequired = TypedDict("_CoilPropsRequired", {"profile": 'ProfileRef', "axis": 'AxisRef', "pitch": float, "turns": float, "operation": 'BooleanMode', "id": str})
_CoilPropsOptional = TypedDict("_CoilPropsOptional", {"right_handed": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CoilProps(_CoilPropsRequired, _CoilPropsOptional):
    pass

#: The keywords of combine(…): the CombineFeature fields, in snake_case.
_CombinePropsRequired = TypedDict("_CombinePropsRequired", {"operation": Literal["intersect", "union", "subtract"], "id": str})
_CombinePropsOptional = TypedDict("_CombinePropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CombineProps(_CombinePropsRequired, _CombinePropsOptional):
    pass

#: The keywords of offsetFaces(…): the OffsetFacesFeature fields, in snake_case.
_OffsetFacesPropsRequired = TypedDict("_OffsetFacesPropsRequired", {"faces": List['TopoRef'], "distance": float, "id": str})
_OffsetFacesPropsOptional = TypedDict("_OffsetFacesPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class OffsetFacesProps(_OffsetFacesPropsRequired, _OffsetFacesPropsOptional):
    pass

#: The keywords of thicken(…): the ThickenFeature fields, in snake_case.
_ThickenPropsRequired = TypedDict("_ThickenPropsRequired", {"distance": float, "id": str})
_ThickenPropsOptional = TypedDict("_ThickenPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ThickenProps(_ThickenPropsRequired, _ThickenPropsOptional):
    pass

#: The keywords of split(…): the SplitFeature fields, in snake_case.
_SplitPropsRequired = TypedDict("_SplitPropsRequired", {"plane": 'PlaneRef', "id": str})
_SplitPropsOptional = TypedDict("_SplitPropsOptional", {"suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SplitProps(_SplitPropsRequired, _SplitPropsOptional):
    pass

#: The keywords of scale(…): the ScaleFeature fields, in snake_case.
_ScalePropsRequired = TypedDict("_ScalePropsRequired", {"factor": float, "id": str})
_ScalePropsOptional = TypedDict("_ScalePropsOptional", {"center": 'Vec3', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class ScaleProps(_ScalePropsRequired, _ScalePropsOptional):
    pass

#: The keywords of rib(…): the RibFeature fields, in snake_case.
_RibPropsRequired = TypedDict("_RibPropsRequired", {"sketch": str, "thickness": float, "depth": float, "operation": 'BooleanMode', "id": str})
_RibPropsOptional = TypedDict("_RibPropsOptional", {"both_sides": bool, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class RibProps(_RibPropsRequired, _RibPropsOptional):
    pass

#: The keywords of subdivBody(…): the SubdivBodyFeature fields, in snake_case.
_SubdivBodyPropsRequired = TypedDict("_SubdivBodyPropsRequired", {"control_points": List['Vec3'], "faces": List[List[float]], "level": float, "id": str})
_SubdivBodyPropsOptional = TypedDict("_SubdivBodyPropsOptional", {"operation": 'BooleanMode', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SubdivBodyProps(_SubdivBodyPropsRequired, _SubdivBodyPropsOptional):
    pass

#: The keywords of meshModifier(…): the MeshModifierFeature fields, in snake_case.
_MeshModifierPropsRequired = TypedDict("_MeshModifierPropsRequired", {"input": str, "modifier": 'MeshModifierSpec', "id": str})
_MeshModifierPropsOptional = TypedDict("_MeshModifierPropsOptional", {"target": str, "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class MeshModifierProps(_MeshModifierPropsRequired, _MeshModifierPropsOptional):
    pass

__MeshBodyProps37Required = TypedDict("__MeshBodyProps37Required", {})
__MeshBodyProps37Optional = TypedDict("__MeshBodyProps37Optional", {"prompt": str, "expert": str, "generationId": str, "fileId": str, "fileName": str}, total=False)
class _MeshBodyProps37(__MeshBodyProps37Required, __MeshBodyProps37Optional):
    pass

#: The keywords of meshBody(…): the MeshBodyFeature fields, in snake_case.
_MeshBodyPropsRequired = TypedDict("_MeshBodyPropsRequired", {"positions": List[float], "indices": List[float], "id": str})
_MeshBodyPropsOptional = TypedDict("_MeshBodyPropsOptional", {"polygons": List[List[float]], "normals": List[float], "uv": List[float], "source_uv": List[float], "source_materials": List['SourceMaterial'], "material_groups": List['SourceMaterialGroup'], "source": '_MeshBodyProps37', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class MeshBodyProps(_MeshBodyPropsRequired, _MeshBodyPropsOptional):
    pass

#: The keywords of generate(…): the GenerateFeature fields, in snake_case.
_GeneratePropsRequired = TypedDict("_GeneratePropsRequired", {"model_id": str, "params": Dict[str, Any], "id": str})
_GeneratePropsOptional = TypedDict("_GeneratePropsOptional", {"refs": Dict[str, str], "provenance": 'GenNodeRecord', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class GenerateProps(_GeneratePropsRequired, _GeneratePropsOptional):
    pass

__PointCloudProps38Required = TypedDict("__PointCloudProps38Required", {})
__PointCloudProps38Optional = TypedDict("__PointCloudProps38Optional", {"format": str, "fileId": str, "fileName": str}, total=False)
class _PointCloudProps38(__PointCloudProps38Required, __PointCloudProps38Optional):
    pass

#: The keywords of pointCloud(…): the PointCloudFeature fields, in snake_case.
_PointCloudPropsRequired = TypedDict("_PointCloudPropsRequired", {"positions": List[float], "id": str})
_PointCloudPropsOptional = TypedDict("_PointCloudPropsOptional", {"colors": List[float], "point_size": float, "source": '_PointCloudProps38', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class PointCloudProps(_PointCloudPropsRequired, _PointCloudPropsOptional):
    pass

__GaussianSplatProps39Required = TypedDict("__GaussianSplatProps39Required", {})
__GaussianSplatProps39Optional = TypedDict("__GaussianSplatProps39Optional", {"format": str, "fileId": str, "fileName": str, "shDegree": float, "splatCount": float}, total=False)
class _GaussianSplatProps39(__GaussianSplatProps39Required, __GaussianSplatProps39Optional):
    pass

#: The keywords of gaussianSplat(…): the GaussianSplatFeature fields, in snake_case.
_GaussianSplatPropsRequired = TypedDict("_GaussianSplatPropsRequired", {"count": float, "positions": List[float], "scales": List[float], "rotations": List[float], "colors": List[float], "id": str})
_GaussianSplatPropsOptional = TypedDict("_GaussianSplatPropsOptional", {"sh_degree": Literal[0, 3, 1, 2], "sh": List[float], "source": '_GaussianSplatProps39', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class GaussianSplatProps(_GaussianSplatPropsRequired, _GaussianSplatPropsOptional):
    pass

__MoleculeProps40Required = TypedDict("__MoleculeProps40Required", {})
__MoleculeProps40Optional = TypedDict("__MoleculeProps40Optional", {"format": str, "fileId": str, "fileName": str, "title": str, "atomCount": float}, total=False)
class _MoleculeProps40(__MoleculeProps40Required, __MoleculeProps40Optional):
    pass

#: The keywords of molecule(…): the MoleculeFeature fields, in snake_case.
_MoleculePropsRequired = TypedDict("_MoleculePropsRequired", {"positions": List[float], "elements": List[float], "bonds": List[float], "id": str})
_MoleculePropsOptional = TypedDict("_MoleculePropsOptional", {"bond_orders": List[float], "chains": List[float], "cell": Tuple[float, float, float, float, float, float], "representation": 'MoleculeRepresentation', "source": '_MoleculeProps40', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class MoleculeProps(_MoleculePropsRequired, _MoleculePropsOptional):
    pass

__SkeletonProps41Required = TypedDict("__SkeletonProps41Required", {})
__SkeletonProps41Optional = TypedDict("__SkeletonProps41Optional", {"format": str, "fileId": str, "fileName": str}, total=False)
class _SkeletonProps41(__SkeletonProps41Required, __SkeletonProps41Optional):
    pass

#: The keywords of skeleton(…): the SkeletonFeature fields, in snake_case.
_SkeletonPropsRequired = TypedDict("_SkeletonPropsRequired", {"positions": List[float], "parents": List[float], "id": str})
_SkeletonPropsOptional = TypedDict("_SkeletonPropsOptional", {"radii": List[float], "node_types": List[float], "source": '_SkeletonProps41', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class SkeletonProps(_SkeletonPropsRequired, _SkeletonPropsOptional):
    pass

__VolumeProps42Required = TypedDict("__VolumeProps42Required", {})
__VolumeProps42Optional = TypedDict("__VolumeProps42Optional", {"format": str, "fileId": str, "fileName": str, "kind": Literal["scalar", "label"]}, total=False)
class _VolumeProps42(__VolumeProps42Required, __VolumeProps42Optional):
    pass

#: The keywords of volume(…): the VolumeFeature fields, in snake_case.
_VolumePropsRequired = TypedDict("_VolumePropsRequired", {"dims": Tuple[float, float, float], "spacing": Tuple[float, float, float], "origin": 'Vec3', "data": List[float], "id": str})
_VolumePropsOptional = TypedDict("_VolumePropsOptional", {"render": Literal["slices", "iso"], "iso": float, "colormap": str, "source": '_VolumeProps42', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class VolumeProps(_VolumePropsRequired, _VolumePropsOptional):
    pass

__GraphProps43Required = TypedDict("__GraphProps43Required", {})
__GraphProps43Optional = TypedDict("__GraphProps43Optional", {"format": str, "fileId": str, "fileName": str, "title": str, "nodeCount": float, "edgeCount": float}, total=False)
class _GraphProps43(__GraphProps43Required, __GraphProps43Optional):
    pass

#: The keywords of graph(…): the GraphFeature fields, in snake_case.
_GraphPropsRequired = TypedDict("_GraphPropsRequired", {"node_positions": List[float], "edges": List[float], "id": str})
_GraphPropsOptional = TypedDict("_GraphPropsOptional", {"node_sizes": List[float], "node_colors": List[float], "node_groups": List[float], "edge_weights": List[float], "directed": bool, "source": '_GraphProps43', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class GraphProps(_GraphPropsRequired, _GraphPropsOptional):
    pass

#: The keywords of pcbTrace(…): the PcbTraceFeature fields, in snake_case.
_PcbTracePropsRequired = TypedDict("_PcbTracePropsRequired", {"path": 'ConductorPathRef', "layer": 'CopperLayerRef', "rule": 'RoutingRule', "width": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str})
_PcbTracePropsOptional = TypedDict("_PcbTracePropsOptional", {"centreline": Literal["arc-through-three-points"], "bias": 'RouteBias', "join": 'OffsetJoin', "cap": 'OffsetCap', "material": 'MaterialDef', "bindings": List['TerminalBinding'], "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class PcbTraceProps(_PcbTracePropsRequired, _PcbTracePropsOptional):
    pass

#: The keywords of generateVia(…): the GenerateViaFeature fields, in snake_case.
_GenerateViaPropsRequired = TypedDict("_GenerateViaPropsRequired", {"at": 'ConductorPathRef', "layers": List['CopperLayerRef'], "drill_mm": float, "pad_diameter_mm": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str})
_GenerateViaPropsOptional = TypedDict("_GenerateViaPropsOptional", {"material": 'MaterialDef', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class GenerateViaProps(_GenerateViaPropsRequired, _GenerateViaPropsOptional):
    pass

#: The keywords of platedHole(…): the PlatedHoleFeature fields, in snake_case.
_PlatedHolePropsRequired = TypedDict("_PlatedHolePropsRequired", {"at": 'ConductorPathRef', "layers": List['CopperLayerRef'], "drill_mm": float, "pad_diameter_mm": float, "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str})
_PlatedHolePropsOptional = TypedDict("_PlatedHolePropsOptional", {"material": 'MaterialDef', "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class PlatedHoleProps(_PlatedHolePropsRequired, _PlatedHolePropsOptional):
    pass

#: The keywords of copperPour(…): the CopperPourFeature fields, in snake_case.
_CopperPourPropsRequired = TypedDict("_CopperPourPropsRequired", {"path": 'ConductorPathRef', "layer": 'CopperLayerRef', "rule": 'RoutingRule', "conductor": 'ConductorElectrical', "operation": 'BooleanMode', "id": str})
_CopperPourPropsOptional = TypedDict("_CopperPourPropsOptional", {"bias": 'RouteBias', "material": 'MaterialDef', "bindings": List['TerminalBinding'], "suppressed": bool, "consumes": List[str], "name": str}, total=False)
class CopperPourProps(_CopperPourPropsRequired, _CopperPourPropsOptional):
    pass

AxisRef = Union['_AxisRef1', '_AxisRef2', '_AxisRef3', '_AxisRef4']

#: How a solid feature combines with existing bodies.
BooleanMode = Literal["new", "add", "cut", "intersect"]

ConstraintKind = Literal["coincident", "parallel", "perpendicular", "distance", "angle", "horizontal", "vertical", "tangent", "equal", "pointOnLine", "midpoint", "pointOnCircle", "symmetric", "horizontalDistance", "verticalDistance", "radius"]

HoleStyle = Literal["simple", "counterbore", "countersink"]

MaterialPreset = Literal["aluminum", "steel", "plastic", "brass", "copper", "chrome", "rubber", "custom"]

MeshModifierSpec = Union['_MeshModifierSpec9', '_MeshModifierSpec10', '_MeshModifierSpec11', '_MeshModifierSpec12', '_MeshModifierSpec13']

OffsetCap = Literal["round", "butt", "square"]

OffsetJoin = Literal["miter", "round", "bevel"]

#: WHERE A SKETCH LIVES. Three kinds, and the third is not a plane at all.
PlaneRef = Union['_PlaneRef15', '_PlaneRef16', '_PlaneRef17']

RouteBias = Literal["x-first", "y-first"]

RoutingRule = Literal["45", "90", "any"]

#: WHICH POINT of the target, once it is flattened onto the sketch plane.
SketchPinAnchor = Literal["vertex", "centroid", "center", "minU", "maxU", "minV", "maxV", "minU_minV", "maxU_minV", "minU_maxV", "maxU_maxV"]

#: WHICH b-rep thing a pin follows. Bodies are named by the FEATURE that produced them (lineage is what survives a parametric edit — a signature match would drift the moment the body moves, which is exactly when a pin has to keep holding). Sub-shapes reuse the document's signature-matched TopoRef, the same handle every other feature uses to say "that face".
SketchPinTarget = Union['_SketchPinTarget20', '_SketchPinTarget21', '_SketchPinTarget22', '_SketchPinTarget23', '_SketchPinTarget24']

SketchSegment = Union['_SketchSegment25', '_SketchSegment26', '_SketchSegment27', '_SketchSegment28', '_SketchSegment29', '_SketchSegment30']

SketchSolveStatus = Literal["ok", "over", "under", "inconsistent"]

SourceTexture = Union['SourceImageTexture', 'SourceDataTexture', 'SourceCompressedTexture']

UnwrapSurface = Union['PlanarSurface', 'CylindricalSurface', 'ConicalSurface', 'SphericalSurface', 'ToroidalSurface']

#: A point or vector in 2D (sketch space).
Vec2 = Tuple[float, float]

#: A point or vector in 3D.
Vec3 = Tuple[float, float, float]

#: Every 3D feature element: its tag → the TypedDict of its keywords.
THREED_ELEMENTS: Dict[str, type] = {
    "code": CodeProps,
    "sketch": SketchProps,
    "extrude": ExtrudeProps,
    "revolve": RevolveProps,
    "sweep": SweepProps,
    "loft": LoftProps,
    "fillet": FilletProps,
    "chamfer": ChamferProps,
    "shell": ShellProps,
    "box": BoxProps,
    "import": ImportProps,
    "externalPart": ExternalPartProps,
    "cylinder": CylinderProps,
    "sphere": SphereProps,
    "cone": ConeProps,
    "makeHuman": MakeHumanProps,
    "linearPattern": LinearPatternProps,
    "circularPattern": CircularPatternProps,
    "pathPattern": PathPatternProps,
    "mirror": MirrorProps,
    "datumPlane": DatumPlaneProps,
    "draft": DraftProps,
    "hole": HoleProps,
    "transform": TransformProps,
    "sheetFlange": SheetFlangeProps,
    "unfold": UnfoldProps,
    "wrapText": WrapTextProps,
    "deleteFace": DeleteFaceProps,
    "fullRound": FullRoundProps,
    "dome": DomeProps,
    "copyBody": CopyBodyProps,
    "thread": ThreadProps,
    "coil": CoilProps,
    "combine": CombineProps,
    "offsetFaces": OffsetFacesProps,
    "thicken": ThickenProps,
    "split": SplitProps,
    "scale": ScaleProps,
    "rib": RibProps,
    "subdivBody": SubdivBodyProps,
    "meshModifier": MeshModifierProps,
    "meshBody": MeshBodyProps,
    "generate": GenerateProps,
    "pointCloud": PointCloudProps,
    "gaussianSplat": GaussianSplatProps,
    "molecule": MoleculeProps,
    "skeleton": SkeletonProps,
    "volume": VolumeProps,
    "graph": GraphProps,
    "pcbTrace": PcbTraceProps,
    "generateVia": GenerateViaProps,
    "platedHole": PlatedHoleProps,
    "copperPour": CopperPourProps,
}
